spring:
  datasource:
    url: jdbc:mysql://39.96.239.189:3306/hardcore_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Zhangge208
  cache:
    type: redis
    redis:
      time-to-live: 60s

  redis:
    database: 0
    host: localhost
    port: 6379
    password: hardcore

logging:
  level:
    com.hardcore.accounting: DEBUG

pagehelper:
  support-methods-arguments: true
