spring:
  datasource:
    url: jdbc:mysql://39.96.239.189:3306/hardcore_test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Zhangge208

logging:
  level:
    com.hardcore.accounting: DEBUG

pagehelper:
  support-methods-arguments: true
